apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stockai-document-pvc
  namespace: stockai-prod
  labels:
    app.kubernetes.io/name: stockai-backend
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard-rwo
