-- StockAI Offline Factory Deployment
-- Machine telemetry persistence required by MachineTelemetryLog entity.
-- Runs after the canonical application schema on a fresh PostgreSQL volume.

CREATE TABLE IF NOT EXISTS machine_telemetry_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_code VARCHAR(50) NOT NULL,
    unit_name VARCHAR(50),
    machine_type VARCHAR(50),
    sequence_number BIGINT,
    machine_status VARCHAR(30) NOT NULL,

    zone1_temp NUMERIC(8,2),
    zone2_temp NUMERIC(8,2),
    zone3_temp NUMERIC(8,2),
    zone4_temp NUMERIC(8,2),
    zone5_temp NUMERIC(8,2),
    zone6_temp NUMERIC(8,2),

    die_temp NUMERIC(8,2),
    melt_pressure_bar NUMERIC(8,2),
    screw_rpm NUMERIC(8,2),
    line_speed_mpm NUMERIC(8,2),
    loom_ppm INTEGER,
    active_power_kw NUMERIC(8,2),
    gsm_measured NUMERIC(8,2),
    denier_deviation NUMERIC(8,2),
    tape_width_mm NUMERIC(8,2),

    anomaly_count INTEGER DEFAULT 0,
    packet_timestamp TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_telemetry_log_mch_time
    ON machine_telemetry_log (machine_code, packet_timestamp);

CREATE INDEX IF NOT EXISTS idx_telemetry_log_time
    ON machine_telemetry_log (packet_timestamp);
