listener 1883
allow_anonymous false
password_file /mosquitto/config/passwd

listener 8883
cafile /mosquitto/config/ca.crt
certfile /mosquitto/config/server.crt
keyfile /mosquitto/config/server.key

persistence true
persistence_location /mosquitto/data/

log_dest stdout
