-- ================================================================
-- SVP StockAI - PostgreSQL Database Schema V2.4
-- Factory + ERP + Inventory + IoT integrated architecture
-- PostgreSQL 14+
-- ================================================================

BEGIN;

SET search_path TO public;

-- ================================================================
-- 1. ORGANIZATION & LOCATION
-- ================================================================

CREATE TABLE IF NOT EXISTS plant (
    plant_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_name    VARCHAR(150) NOT NULL,
    city          VARCHAR(100),
    state         VARCHAR(100),
    country       VARCHAR(100),
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_plant_name UNIQUE (plant_name)
);

CREATE TABLE IF NOT EXISTS warehouse (
    warehouse_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id       BIGINT NOT NULL REFERENCES plant(plant_id),
    warehouse_name VARCHAR(150) NOT NULL,
    type           VARCHAR(20) NOT NULL CHECK (type IN ('Raw','FG','Both')),
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_warehouse_plant_name UNIQUE (plant_id, warehouse_name)
);

CREATE TABLE IF NOT EXISTS location_rack (
    rack_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT NOT NULL REFERENCES warehouse(warehouse_id),
    rack_code    VARCHAR(50) NOT NULL,
    is_active    BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_rack_warehouse_code UNIQUE (warehouse_id, rack_code)
);

CREATE TABLE IF NOT EXISTS location_shelf (
    shelf_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rack_id    BIGINT NOT NULL REFERENCES location_rack(rack_id),
    shelf_code VARCHAR(50) NOT NULL,
    is_active  BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_shelf_rack_code UNIQUE (rack_id, shelf_code)
);

CREATE TABLE IF NOT EXISTS location_bin (
    bin_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shelf_id  BIGINT NOT NULL REFERENCES location_shelf(shelf_id),
    bin_code  VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_bin_shelf_code UNIQUE (shelf_id, bin_code)
);

-- ================================================================
-- 2. MASTER DATA
-- ================================================================

CREATE TABLE IF NOT EXISTS material_category (
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL,
    category_type VARCHAR(30) NOT NULL
        CHECK (category_type IN ('Raw','Additive','Packaging','Other')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_material_category_name UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS unit_of_measure (
    uom_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uom_code VARCHAR(20) NOT NULL UNIQUE,
    uom_type VARCHAR(30) NOT NULL
        CHECK (uom_type IN ('Weight','Quantity','Length','Area','Other'))
);

CREATE TABLE IF NOT EXISTS raw_material (
    material_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     BIGINT NOT NULL REFERENCES material_category(category_id),
    default_uom_id  BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    material_name   VARCHAR(150) NOT NULL,
    material_code   VARCHAR(50) NOT NULL UNIQUE,
    standard_cost   NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (standard_cost >= 0),
    reorder_level   NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (reorder_level >= 0),
    safety_stock    NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (safety_stock >= 0),
    lead_time_days  INTEGER NOT NULL DEFAULT 0 CHECK (lead_time_days >= 0),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_category (
    prod_cat_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL UNIQUE,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS finished_product (
    product_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prod_cat_id     BIGINT NOT NULL REFERENCES product_category(prod_cat_id),
    default_uom_id  BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    product_name    VARCHAR(150) NOT NULL,
    product_code    VARCHAR(50) NOT NULL UNIQUE,
    standard_cost   NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (standard_cost >= 0),
    selling_price   NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (selling_price >= 0),
    reorder_level   NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (reorder_level >= 0),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_specification (
    specification_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id                    BIGINT NOT NULL REFERENCES finished_product(product_id) ON DELETE CASCADE,
    version                       VARCHAR(50) NOT NULL DEFAULT '1.0',
    effective_from                DATE,
    effective_to                  DATE,
    bag_capacity_kg               NUMERIC(18,4),
    bag_width_mm                  NUMERIC(18,4),
    bag_length_mm                 NUMERIC(18,4),
    target_empty_weight_g         NUMERIC(18,4),
    min_empty_weight_g            NUMERIC(18,4),
    max_empty_weight_g            NUMERIC(18,4),
    target_gsm                    NUMERIC(18,4),
    min_gsm                       NUMERIC(18,4),
    max_gsm                       NUMERIC(18,4),
    target_output_bags_per_kg     NUMERIC(18,4),
    min_output_bags_per_kg        NUMERIC(18,4),
    max_output_bags_per_kg        NUMERIC(18,4),
    target_scrap_percentage       NUMERIC(7,3),
    min_scrap_percentage          NUMERIC(7,3),
    max_scrap_percentage          NUMERIC(7,3),
    is_active                     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_product_spec_version UNIQUE (product_id, version),
    CONSTRAINT chk_product_spec_dates
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from),
    CONSTRAINT chk_product_spec_scrap
        CHECK (
            target_scrap_percentage IS NULL OR
            (target_scrap_percentage >= 0 AND target_scrap_percentage <= 100)
        )
);

CREATE TABLE IF NOT EXISTS supplier (
    supplier_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR(150) NOT NULL,
    gst_no        VARCHAR(30) UNIQUE,
    email         VARCHAR(255),
    phone         VARCHAR(30),
    address       TEXT,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS supplier_address (
    supplier_address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id         BIGINT NOT NULL REFERENCES supplier(supplier_id) ON DELETE CASCADE,
    address_type        VARCHAR(30) NOT NULL
        CHECK (address_type IN ('Office','Billing','Warehouse','Other')),
    address_line1       VARCHAR(255) NOT NULL,
    address_line2       VARCHAR(255),
    city                VARCHAR(100),
    state               VARCHAR(100),
    country             VARCHAR(100),
    postal_code         VARCHAR(20),
    is_default          BOOLEAN NOT NULL DEFAULT FALSE,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS supplier_contact (
    supplier_contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id         BIGINT NOT NULL REFERENCES supplier(supplier_id) ON DELETE CASCADE,
    contact_name        VARCHAR(150) NOT NULL,
    contact_role        VARCHAR(30)
        CHECK (contact_role IN ('Purchase','Accounts','Sales','Other')),
    email               VARCHAR(255),
    phone               VARCHAR(30),
    is_primary          BOOLEAN NOT NULL DEFAULT FALSE,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS customer (
    customer_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(150) NOT NULL,
    customer_code VARCHAR(50) NOT NULL UNIQUE,
    email         VARCHAR(255),
    phone         VARCHAR(30),
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customer_address (
    address_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT NOT NULL REFERENCES customer(customer_id) ON DELETE CASCADE,
    address_type VARCHAR(20) NOT NULL CHECK (address_type IN ('Billing','Shipping')),
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255),
    city          VARCHAR(100),
    state         VARCHAR(100),
    country       VARCHAR(100),
    postal_code   VARCHAR(20),
    is_default    BOOLEAN NOT NULL DEFAULT FALSE,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS vehicle (
    vehicle_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_number VARCHAR(50) NOT NULL UNIQUE,
    vehicle_type   VARCHAR(50),
    capacity       NUMERIC(18,3) CHECK (capacity >= 0),
    capacity_uom_id BIGINT REFERENCES unit_of_measure(uom_id),
    is_active      BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS driver (
    driver_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_name    VARCHAR(150) NOT NULL,
    license_number VARCHAR(80) NOT NULL UNIQUE,
    license_expiry DATE,
    phone          VARCHAR(30),
    is_active      BOOLEAN NOT NULL DEFAULT TRUE
);

-- ================================================================
-- 3. USER, SECURITY & APPROVALS
-- ================================================================

CREATE TABLE IF NOT EXISTS app_role (
    role_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(100) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS permission (
    permission_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_name    VARCHAR(100) NOT NULL,
    permission_name VARCHAR(100) NOT NULL,
    CONSTRAINT uq_permission_module_name UNIQUE (module_name, permission_name)
);

CREATE TABLE IF NOT EXISTS role_permission (
    rp_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id       BIGINT NOT NULL REFERENCES app_role(role_id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permission(permission_id) ON DELETE CASCADE,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_role_permission UNIQUE (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS app_user (
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id  BIGINT REFERENCES plant(plant_id),
    user_name VARCHAR(100) NOT NULL UNIQUE,
    email     VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    mfa_secret VARCHAR(255),
    mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_role (
    ur_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES app_role(role_id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_user_role UNIQUE (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS user_mfa (
    mfa_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    mfa_type VARCHAR(20) NOT NULL CHECK (mfa_type IN ('TOTP','SMS','Email')),
    is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_user_mfa_type UNIQUE (user_id, mfa_type)
);

CREATE TABLE IF NOT EXISTS login_attempt (
    attempt_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT REFERENCES app_user(user_id) ON DELETE SET NULL,
    ip_address    INET,
    is_successful BOOLEAN NOT NULL,
    attempted_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_session (
    session_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    session_token TEXT NOT NULL UNIQUE,
    expires_at    TIMESTAMPTZ NOT NULL,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS user_notification_pref (
    pref_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL UNIQUE REFERENCES app_user(user_id) ON DELETE CASCADE,
    email_enabled    BOOLEAN NOT NULL DEFAULT TRUE,
    sms_enabled      BOOLEAN NOT NULL DEFAULT FALSE,
    whatsapp_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    inapp_enabled    BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS approval_workflow (
    workflow_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_name VARCHAR(150) NOT NULL,
    entity_type   VARCHAR(100) NOT NULL,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_approval_workflow UNIQUE (workflow_name, entity_type)
);

CREATE TABLE IF NOT EXISTS approval_request (
    approval_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT NOT NULL REFERENCES approval_workflow(workflow_id),
    requested_by BIGINT REFERENCES app_user(user_id),
    entity_type VARCHAR(100) NOT NULL,
    entity_id   VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Pending'
        CHECK (status IN ('Pending','Approved','Rejected','Cancelled')),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS approval_action (
    approval_action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_request_id BIGINT NOT NULL REFERENCES approval_request(approval_request_id) ON DELETE CASCADE,
    approver_id BIGINT REFERENCES app_user(user_id),
    action VARCHAR(20) NOT NULL CHECK (action IN ('Approve','Reject')),
    comments TEXT,
    acted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ================================================================
-- 4. PROCUREMENT
-- ================================================================

CREATE TABLE IF NOT EXISTS supplier_material (
    supplier_material_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL REFERENCES supplier(supplier_id),
    material_id BIGINT NOT NULL REFERENCES raw_material(material_id),
    purchase_rate NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (purchase_rate >= 0),
    lead_time_days INTEGER NOT NULL DEFAULT 0 CHECK (lead_time_days >= 0),
    minimum_order_qty NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (minimum_order_qty >= 0),
    is_preferred BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_supplier_material UNIQUE (supplier_id, material_id)
);

CREATE TABLE IF NOT EXISTS purchase_order (
    po_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL REFERENCES supplier(supplier_id),
    plant_id    BIGINT NOT NULL REFERENCES plant(plant_id),
    po_number   VARCHAR(50) NOT NULL UNIQUE,
    po_date     DATE NOT NULL DEFAULT CURRENT_DATE,
    status      VARCHAR(20) NOT NULL DEFAULT 'Draft'
        CHECK (status IN ('Draft','Approved','Closed','Cancelled')),
    total_amount NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    created_by  BIGINT REFERENCES app_user(user_id),
    updated_by  BIGINT REFERENCES app_user(user_id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS purchase_order_item (
    po_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id      BIGINT NOT NULL REFERENCES purchase_order(po_id) ON DELETE CASCADE,
    material_id BIGINT NOT NULL REFERENCES raw_material(material_id),
    uom_id     BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    quantity   NUMERIC(18,4) NOT NULL CHECK (quantity > 0),
    rate       NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (rate >= 0)
);

CREATE TABLE IF NOT EXISTS goods_receipt (
    gr_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id       BIGINT NOT NULL REFERENCES purchase_order(po_id),
    warehouse_id BIGINT NOT NULL REFERENCES warehouse(warehouse_id),
    gr_number   VARCHAR(50) NOT NULL UNIQUE,
    gr_date     DATE NOT NULL DEFAULT CURRENT_DATE,
    received_by BIGINT REFERENCES app_user(user_id),
    status      VARCHAR(20) NOT NULL DEFAULT 'Open'
        CHECK (status IN ('Open','Closed'))
);

CREATE TABLE IF NOT EXISTS goods_receipt_item (
    gr_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gr_id      BIGINT NOT NULL REFERENCES goods_receipt(gr_id) ON DELETE CASCADE,
    po_item_id BIGINT NOT NULL REFERENCES purchase_order_item(po_item_id),
    material_id BIGINT NOT NULL REFERENCES raw_material(material_id),
    uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    ordered_qty NUMERIC(18,4) NOT NULL CHECK (ordered_qty >= 0),
    received_qty NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (received_qty >= 0),
    pending_qty NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (pending_qty >= 0),
    CONSTRAINT chk_gr_pending CHECK (pending_qty <= ordered_qty)
);

-- ================================================================
-- 5. RAW MATERIAL BATCHES
-- ================================================================

CREATE TABLE IF NOT EXISTS material_batch (
    batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id BIGINT NOT NULL REFERENCES raw_material(material_id),
    supplier_id BIGINT REFERENCES supplier(supplier_id),
    po_item_id BIGINT REFERENCES purchase_order_item(po_item_id),
    batch_no VARCHAR(80) NOT NULL UNIQUE,
    lot_number VARCHAR(80),
    expiry_date DATE,
    initial_weight_kg NUMERIC(18,4) CHECK (initial_weight_kg IS NULL OR initial_weight_kg >= 0),
    current_weight_kg NUMERIC(18,4) CHECK (current_weight_kg IS NULL OR current_weight_kg >= 0),
    unit_cost NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),
    received_at TIMESTAMPTZ,
    quality_status VARCHAR(20) NOT NULL DEFAULT 'Available'
        CHECK (quality_status IN ('Available','Hold','Quarantine','Rejected','Expired')),
    status VARCHAR(20) NOT NULL DEFAULT 'Available'
        CHECK (status IN ('Available','Hold','Quarantine','Rejected','Expired','Consumed','Closed')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_material_batch_lot UNIQUE (lot_number)
);

-- ================================================================
-- 6. PRODUCTION MASTER / COMPOUNDING / FACTORY UNITS
-- ================================================================

CREATE TABLE IF NOT EXISTS bom (
    bom_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES finished_product(product_id),
    version VARCHAR(50) NOT NULL,
    effective_from DATE,
    effective_to DATE,
    yield_quantity NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (yield_quantity >= 0),
    status VARCHAR(20) NOT NULL DEFAULT 'Draft'
        CHECK (status IN ('Draft','Active','Retired')),
    CONSTRAINT uq_bom_product_version UNIQUE (product_id, version),
    CONSTRAINT chk_bom_dates
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from)
);

CREATE TABLE IF NOT EXISTS bom_item (
    bom_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_id BIGINT NOT NULL REFERENCES bom(bom_id) ON DELETE CASCADE,
    material_id BIGINT NOT NULL REFERENCES raw_material(material_id),
    uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    quantity NUMERIC(18,4) NOT NULL CHECK (quantity > 0),
    scrap_percentage NUMERIC(7,3) NOT NULL DEFAULT 0
        CHECK (scrap_percentage >= 0 AND scrap_percentage <= 100),
    is_optional BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_bom_material UNIQUE (bom_id, material_id)
);

CREATE TABLE IF NOT EXISTS compounding_bom (
    compounding_bom_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_code VARCHAR(50) NOT NULL,
    version VARCHAR(50) NOT NULL,
    effective_from DATE,
    effective_to DATE,
    target_batch_weight_kg NUMERIC(18,4) NOT NULL CHECK (target_batch_weight_kg > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'Draft'
        CHECK (status IN ('Draft','Active','Retired')),
    created_by BIGINT REFERENCES app_user(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_compounding_bom_code_version UNIQUE (bom_code, version),
    CONSTRAINT chk_compounding_bom_dates
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from)
);

CREATE TABLE IF NOT EXISTS compounding_bom_item (
    compounding_bom_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compounding_bom_id BIGINT NOT NULL REFERENCES compounding_bom(compounding_bom_id) ON DELETE CASCADE,
    material_id BIGINT NOT NULL REFERENCES raw_material(material_id),
    percentage NUMERIC(7,4) NOT NULL CHECK (percentage >= 0 AND percentage <= 100),
    target_quantity_kg NUMERIC(18,4) NOT NULL CHECK (target_quantity_kg > 0),
    is_required BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_compounding_bom_material UNIQUE (compounding_bom_id, material_id)
);

CREATE TABLE IF NOT EXISTS compounding_batch (
    compounding_batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_code VARCHAR(80) NOT NULL UNIQUE,
    compounding_bom_id BIGINT NOT NULL REFERENCES compounding_bom(compounding_bom_id),
    target_weight_kg NUMERIC(18,4) NOT NULL CHECK (target_weight_kg > 0),
    actual_weight_kg NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (actual_weight_kg >= 0),
    status VARCHAR(20) NOT NULL DEFAULT 'Planned'
        CHECK (status IN ('Planned','InProgress','Completed','Hold','Rejected','Cancelled')),
    created_by BIGINT REFERENCES app_user(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS compounding_batch_material (
    compounding_batch_material_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compounding_batch_id BIGINT NOT NULL REFERENCES compounding_batch(compounding_batch_id) ON DELETE CASCADE,
    material_batch_id BIGINT NOT NULL REFERENCES material_batch(batch_id),
    required_qty_kg NUMERIC(18,4) NOT NULL CHECK (required_qty_kg > 0),
    consumed_qty_kg NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (consumed_qty_kg >= 0),
    CONSTRAINT uq_compounding_batch_material UNIQUE (compounding_batch_id, material_batch_id)
);

CREATE TABLE IF NOT EXISTS production_unit (
    unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id BIGINT NOT NULL REFERENCES plant(plant_id),
    unit_code VARCHAR(50) NOT NULL,
    unit_name VARCHAR(100) NOT NULL,
    unit_type VARCHAR(30) NOT NULL
        CHECK (unit_type IN ('Extrusion','Weaving','Conversion','Other')),
    sequence_no INTEGER NOT NULL CHECK (sequence_no > 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_production_unit_code UNIQUE (unit_code),
    CONSTRAINT uq_production_unit_plant_sequence UNIQUE (plant_id, sequence_no)
);

CREATE TABLE IF NOT EXISTS machine (
    machine_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id BIGINT NOT NULL REFERENCES production_unit(unit_id),
    machine_code VARCHAR(50) NOT NULL UNIQUE,
    machine_name VARCHAR(150) NOT NULL,
    machine_type VARCHAR(100),
    rated_capacity NUMERIC(18,4) CHECK (rated_capacity IS NULL OR rated_capacity >= 0),
    capacity_uom_id BIGINT REFERENCES unit_of_measure(uom_id),
    status VARCHAR(30) NOT NULL DEFAULT 'Available'
        CHECK (status IN ('Available','Running','Maintenance','Stopped','Fault','Retired')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS production_run (
    production_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id BIGINT NOT NULL REFERENCES plant(plant_id),
    bom_id BIGINT NOT NULL REFERENCES bom(bom_id),
    compounding_batch_id BIGINT REFERENCES compounding_batch(compounding_batch_id),
    production_number VARCHAR(50) NOT NULL UNIQUE,
    start_datetime TIMESTAMPTZ,
    end_datetime TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'Planned'
        CHECK (status IN ('Planned','InProgress','Completed','Cancelled','Blocked')),
    planned_qty NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (planned_qty >= 0),
    actual_qty NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (actual_qty >= 0),
    input_weight_kg NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (input_weight_kg >= 0),
    output_weight_kg NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (output_weight_kg >= 0),
    scrap_weight_kg NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (scrap_weight_kg >= 0),
    yield_percentage NUMERIC(7,3) CHECK (yield_percentage IS NULL OR (yield_percentage >= 0 AND yield_percentage <= 100)),
    bags_produced NUMERIC(18,4) CHECK (bags_produced IS NULL OR bags_produced >= 0),
    bags_per_kg NUMERIC(18,4) CHECK (bags_per_kg IS NULL OR bags_per_kg >= 0),
    created_by BIGINT REFERENCES app_user(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_production_dates
        CHECK (end_datetime IS NULL OR start_datetime IS NULL OR end_datetime >= start_datetime)
);

CREATE TABLE IF NOT EXISTS production_stage (
    stage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_id BIGINT NOT NULL REFERENCES production_run(production_id) ON DELETE CASCADE,
    unit_id BIGINT NOT NULL REFERENCES production_unit(unit_id),
    machine_id BIGINT REFERENCES machine(machine_id),
    sequence_no INTEGER NOT NULL CHECK (sequence_no > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'Pending'
        CHECK (status IN ('Pending','Ready','Running','Completed','Blocked','Failed','Cancelled')),
    input_weight_kg NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (input_weight_kg >= 0),
    output_weight_kg NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (output_weight_kg >= 0),
    scrap_weight_kg NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (scrap_weight_kg >= 0),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_production_stage_sequence UNIQUE (production_id, sequence_no),
    CONSTRAINT chk_stage_dates
        CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at)
);

CREATE TABLE IF NOT EXISTS production_material (
    pm_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_id BIGINT NOT NULL REFERENCES production_run(production_id) ON DELETE CASCADE,
    batch_id BIGINT NOT NULL REFERENCES material_batch(batch_id),
    required_qty NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (required_qty >= 0),
    issued_qty NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (issued_qty >= 0),
    wastage_qty NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (wastage_qty >= 0)
);

CREATE TABLE IF NOT EXISTS unit_operation (
    operation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_id BIGINT NOT NULL REFERENCES production_run(production_id) ON DELETE CASCADE,
    stage_id BIGINT REFERENCES production_stage(stage_id),
    unit_id BIGINT NOT NULL REFERENCES production_unit(unit_id),
    machine_id BIGINT REFERENCES machine(machine_id),
    compounding_batch_id BIGINT REFERENCES compounding_batch(compounding_batch_id),
    operation_type VARCHAR(30) NOT NULL DEFAULT 'Production',
    input_weight_kg NUMERIC(18,4) NOT NULL CHECK (input_weight_kg >= 0),
    output_weight_kg NUMERIC(18,4) NOT NULL CHECK (output_weight_kg >= 0),
    scrap_weight_kg NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (scrap_weight_kg >= 0),
    logged_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_by BIGINT REFERENCES app_user(user_id),
    CONSTRAINT chk_unit_operation_balance
        CHECK (ABS(input_weight_kg - (output_weight_kg + scrap_weight_kg)) <= 0.0001),
    CONSTRAINT chk_unit_operation_dates
        CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at)
);

CREATE TABLE IF NOT EXISTS finished_batch (
    finished_batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES finished_product(product_id),
    batch_no VARCHAR(80) NOT NULL UNIQUE,
    production_date DATE NOT NULL,
    expiry_date DATE,
    qty_produced NUMERIC(18,4) NOT NULL CHECK (qty_produced >= 0),
    qty_rejected NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (qty_rejected >= 0),
    input_weight_kg NUMERIC(18,4) CHECK (input_weight_kg IS NULL OR input_weight_kg >= 0),
    output_weight_kg NUMERIC(18,4) CHECK (output_weight_kg IS NULL OR output_weight_kg >= 0),
    scrap_weight_kg NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (scrap_weight_kg >= 0),
    bags_produced NUMERIC(18,4) CHECK (bags_produced IS NULL OR bags_produced >= 0),
    average_bag_weight_g NUMERIC(18,4) CHECK (average_bag_weight_g IS NULL OR average_bag_weight_g >= 0),
    bags_per_kg NUMERIC(18,4) CHECK (bags_per_kg IS NULL OR bags_per_kg >= 0),
    quality_status VARCHAR(30) NOT NULL DEFAULT 'Hold'
        CHECK (quality_status IN ('Hold','Available','Rejected','Quarantine','Released')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_finished_batch_dates
        CHECK (expiry_date IS NULL OR expiry_date >= production_date),
    CONSTRAINT chk_finished_batch_rejected
        CHECK (qty_rejected <= qty_produced)
);

CREATE TABLE IF NOT EXISTS production_output (
    output_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_id BIGINT NOT NULL REFERENCES production_run(production_id) ON DELETE CASCADE,
    finished_batch_id BIGINT NOT NULL UNIQUE REFERENCES finished_batch(finished_batch_id),
    produced_qty NUMERIC(18,4) NOT NULL CHECK (produced_qty > 0),
    output_weight_kg NUMERIC(18,4) CHECK (output_weight_kg IS NULL OR output_weight_kg >= 0),
    output_bags NUMERIC(18,4) CHECK (output_bags IS NULL OR output_bags >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS batch_genealogy (
    genealogy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finished_batch_id BIGINT NOT NULL REFERENCES finished_batch(finished_batch_id) ON DELETE CASCADE,
    raw_material_batch_id BIGINT REFERENCES material_batch(batch_id),
    compounding_batch_id BIGINT REFERENCES compounding_batch(compounding_batch_id),
    production_id BIGINT NOT NULL REFERENCES production_run(production_id),
    unit_operation_id BIGINT REFERENCES unit_operation(operation_id),
    quantity_consumed NUMERIC(18,4) NOT NULL CHECK (quantity_consumed > 0),
    quantity_uom_id BIGINT REFERENCES unit_of_measure(uom_id),
    CONSTRAINT chk_genealogy_source
        CHECK (raw_material_batch_id IS NOT NULL OR compounding_batch_id IS NOT NULL)
);

-- ================================================================
-- 7. INVENTORY / STOCK / DOUBLE-ENTRY LEDGER
-- ================================================================

CREATE TABLE IF NOT EXISTS inventory (
    inventory_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_batch_id BIGINT REFERENCES material_batch(batch_id),
    finished_batch_id BIGINT REFERENCES finished_batch(finished_batch_id),
    bin_id BIGINT NOT NULL REFERENCES location_bin(bin_id),
    quantity_on_hand NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (quantity_on_hand >= 0),
    reserved_qty NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (reserved_qty >= 0),
    quality_status VARCHAR(30),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_inventory_exactly_one_batch CHECK (
        (material_batch_id IS NOT NULL AND finished_batch_id IS NULL) OR
        (material_batch_id IS NULL AND finished_batch_id IS NOT NULL)
    ),
    CONSTRAINT chk_inventory_reserved CHECK (reserved_qty <= quantity_on_hand),
    CONSTRAINT uq_inventory_material_bin UNIQUE (material_batch_id, bin_id),
    CONSTRAINT uq_inventory_finished_bin UNIQUE (finished_batch_id, bin_id)
);

CREATE TABLE IF NOT EXISTS stock_transfer (
    transfer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_warehouse_id BIGINT NOT NULL REFERENCES warehouse(warehouse_id),
    to_warehouse_id BIGINT NOT NULL REFERENCES warehouse(warehouse_id),
    transfer_number VARCHAR(50) NOT NULL UNIQUE,
    transfer_date DATE NOT NULL DEFAULT CURRENT_DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Draft'
        CHECK (status IN ('Draft','Completed','Cancelled')),
    created_by BIGINT REFERENCES app_user(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_transfer_different_warehouses CHECK (from_warehouse_id <> to_warehouse_id)
);

CREATE TABLE IF NOT EXISTS stock_transfer_item (
    sti_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id BIGINT NOT NULL REFERENCES stock_transfer(transfer_id) ON DELETE CASCADE,
    material_batch_id BIGINT REFERENCES material_batch(batch_id),
    finished_batch_id BIGINT REFERENCES finished_batch(finished_batch_id),
    from_bin_id BIGINT NOT NULL REFERENCES location_bin(bin_id),
    to_bin_id BIGINT NOT NULL REFERENCES location_bin(bin_id),
    quantity NUMERIC(18,4) NOT NULL CHECK (quantity > 0),
    uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    CONSTRAINT chk_transfer_item_exactly_one_batch CHECK (
        (material_batch_id IS NOT NULL AND finished_batch_id IS NULL) OR
        (material_batch_id IS NULL AND finished_batch_id IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS inventory_transaction (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id BIGINT NOT NULL REFERENCES inventory(inventory_id),
    stock_transfer_item_id BIGINT REFERENCES stock_transfer_item(sti_id),
    production_material_id BIGINT REFERENCES production_material(pm_id),
    production_output_id BIGINT REFERENCES production_output(output_id),
    dispatch_item_id BIGINT,
    transaction_type VARCHAR(30) NOT NULL
        CHECK (transaction_type IN (
            'Purchase','ProdConsumption','ProdOutput','TransferIn','TransferOut',
            'SalesDispatch','Return','Scrap','Adjustment','Reservation','Release'
        )),
    reference_type VARCHAR(30)
        CHECK (reference_type IN ('PO','Production','Dispatch','Transfer','Return','Other')),
    reference_id VARCHAR(100),
    quantity NUMERIC(18,4) NOT NULL CHECK (quantity > 0),
    direction VARCHAR(10) NOT NULL CHECK (direction IN ('IN','OUT')),
    unit_cost NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),
    transaction_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT REFERENCES app_user(user_id),
    CONSTRAINT chk_inventory_tx_source_count CHECK (
        ((stock_transfer_item_id IS NOT NULL)::INT +
         (production_material_id IS NOT NULL)::INT +
         (production_output_id IS NOT NULL)::INT +
         (dispatch_item_id IS NOT NULL)::INT) <= 1
    )
);

CREATE TABLE IF NOT EXISTS inventory_ledger_transaction (
    ledger_transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_group_id UUID NOT NULL UNIQUE,
    transaction_type VARCHAR(30) NOT NULL
        CHECK (transaction_type IN (
            'Purchase','Production','Transfer','Dispatch','Return','Scrap','Adjustment','Reservation','Release'
        )),
    reference_type VARCHAR(30),
    reference_id VARCHAR(100),
    transaction_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT REFERENCES app_user(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory_ledger_entry (
    ledger_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_transaction_id BIGINT NOT NULL REFERENCES inventory_ledger_transaction(ledger_transaction_id) ON DELETE RESTRICT,
    inventory_id BIGINT REFERENCES inventory(inventory_id),
    entry_type VARCHAR(10) NOT NULL CHECK (entry_type IN ('DEBIT','CREDIT')),
    quantity NUMERIC(18,4) NOT NULL CHECK (quantity > 0),
    unit_cost NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory_reservation (
    reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id BIGINT NOT NULL,
    inventory_id BIGINT NOT NULL REFERENCES inventory(inventory_id),
    reserved_qty NUMERIC(18,4) NOT NULL CHECK (reserved_qty > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'Active'
        CHECK (status IN ('Active','Released','Consumed','Cancelled')),
    reserved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    released_at TIMESTAMPTZ
);

-- ================================================================
-- 8. QUALITY CONTROL
-- ================================================================

CREATE TABLE IF NOT EXISTS qc_specification (
    qc_specification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES finished_product(product_id) ON DELETE CASCADE,
    inspection_type VARCHAR(20) NOT NULL
        CHECK (inspection_type IN ('Incoming','InProcess','Final')),
    parameter_name VARCHAR(150) NOT NULL,
    minimum_value NUMERIC(18,6),
    maximum_value NUMERIC(18,6),
    target_value NUMERIC(18,6),
    measurement_unit VARCHAR(30),
    specification TEXT,
    is_critical BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_qc_spec_range
        CHECK (minimum_value IS NULL OR maximum_value IS NULL OR minimum_value <= maximum_value)
);

CREATE TABLE IF NOT EXISTS quality_inspection (
    inspection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_batch_id BIGINT REFERENCES material_batch(batch_id),
    production_id BIGINT REFERENCES production_run(production_id),
    finished_batch_id BIGINT REFERENCES finished_batch(finished_batch_id),
    inspection_type VARCHAR(20) NOT NULL
        CHECK (inspection_type IN ('Incoming','InProcess','Final')),
    inspection_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    inspected_by BIGINT REFERENCES app_user(user_id),
    status VARCHAR(20) NOT NULL DEFAULT 'Pass'
        CHECK (status IN ('Pass','Fail','Partial','Pending')),
    remarks TEXT,
    CONSTRAINT chk_qc_exactly_one_target CHECK (
        ((material_batch_id IS NOT NULL)::INT +
         (production_id IS NOT NULL)::INT +
         (finished_batch_id IS NOT NULL)::INT) = 1
    ),
    CONSTRAINT chk_qc_type_target CHECK (
        (inspection_type = 'Incoming' AND material_batch_id IS NOT NULL) OR
        (inspection_type = 'InProcess' AND production_id IS NOT NULL) OR
        (inspection_type = 'Final' AND finished_batch_id IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS quality_inspection_item (
    qi_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_id BIGINT NOT NULL REFERENCES quality_inspection(inspection_id) ON DELETE CASCADE,
    qc_specification_id BIGINT REFERENCES qc_specification(qc_specification_id),
    parameter_name VARCHAR(150) NOT NULL,
    minimum_value NUMERIC(18,6),
    maximum_value NUMERIC(18,6),
    observed_value NUMERIC(18,6),
    measurement_unit VARCHAR(30),
    target_value NUMERIC(18,6),
    specification TEXT,
    result VARCHAR(10) CHECK (result IN ('Pass','Fail','Pending')),
    is_critical BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS rejection_record (
    rejection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_id BIGINT NOT NULL REFERENCES quality_inspection(inspection_id),
    material_batch_id BIGINT REFERENCES material_batch(batch_id),
    finished_batch_id BIGINT REFERENCES finished_batch(finished_batch_id),
    rejection_qty NUMERIC(18,4) NOT NULL CHECK (rejection_qty > 0),
    reason TEXT NOT NULL,
    disposition VARCHAR(20) NOT NULL
        CHECK (disposition IN ('Reuse','Return','Scrap','Rework')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_rejection_exactly_one_batch CHECK (
        (material_batch_id IS NOT NULL AND finished_batch_id IS NULL) OR
        (material_batch_id IS NULL AND finished_batch_id IS NOT NULL)
    )
);

-- ================================================================
-- 9. PALLET / BARCODE
-- ================================================================

CREATE TABLE IF NOT EXISTS pallet (
    pallet_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pallet_code VARCHAR(80) NOT NULL UNIQUE,
    barcode VARCHAR(150) NOT NULL UNIQUE,
    warehouse_id BIGINT REFERENCES warehouse(warehouse_id),
    bin_id BIGINT REFERENCES location_bin(bin_id),
    status VARCHAR(20) NOT NULL DEFAULT 'Open'
        CHECK (status IN ('Open','Stored','Allocated','Dispatched','Closed','Cancelled')),
    created_by BIGINT REFERENCES app_user(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pallet_item (
    pallet_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pallet_id BIGINT NOT NULL REFERENCES pallet(pallet_id) ON DELETE CASCADE,
    finished_batch_id BIGINT NOT NULL REFERENCES finished_batch(finished_batch_id),
    quantity NUMERIC(18,4) NOT NULL CHECK (quantity > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_pallet_batch UNIQUE (pallet_id, finished_batch_id)
);

-- ================================================================
-- 10. SALES & ORDERS
-- ================================================================

CREATE TABLE IF NOT EXISTS customer_order (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customer(customer_id),
    plant_id BIGINT NOT NULL REFERENCES plant(plant_id),
    billing_address_id BIGINT REFERENCES customer_address(address_id),
    shipping_address_id BIGINT REFERENCES customer_address(address_id),
    billing_address_snapshot JSONB,
    shipping_address_snapshot JSONB,
    order_number VARCHAR(50) NOT NULL UNIQUE,
    order_date DATE NOT NULL DEFAULT CURRENT_DATE,
    required_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Open'
        CHECK (status IN ('Open','Partial','Closed','Cancelled')),
    subtotal NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    discount_amount NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    tax_amount NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    grand_total NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (grand_total >= 0),
    payment_status VARCHAR(30),
    created_by BIGINT REFERENCES app_user(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_order_dates
        CHECK (required_date IS NULL OR required_date >= order_date)
);

CREATE TABLE IF NOT EXISTS customer_order_item (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES customer_order(order_id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES finished_product(product_id),
    ordered_qty NUMERIC(18,4) NOT NULL CHECK (ordered_qty > 0),
    fulfilled_qty NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (fulfilled_qty >= 0),
    pending_qty NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (pending_qty >= 0),
    rate NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (rate >= 0),
    discount_amount NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    tax_amount NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    CONSTRAINT chk_order_item_fulfilled CHECK (fulfilled_qty <= ordered_qty),
    CONSTRAINT chk_order_item_pending CHECK (pending_qty <= ordered_qty)
);

CREATE TABLE IF NOT EXISTS order_allocation (
    allocation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id BIGINT NOT NULL REFERENCES customer_order_item(order_item_id) ON DELETE CASCADE,
    finished_batch_id BIGINT NOT NULL REFERENCES finished_batch(finished_batch_id),
    warehouse_id BIGINT NOT NULL REFERENCES warehouse(warehouse_id),
    bin_id BIGINT NOT NULL REFERENCES location_bin(bin_id),
    pallet_id BIGINT REFERENCES pallet(pallet_id),
    allocated_qty NUMERIC(18,4) NOT NULL CHECK (allocated_qty > 0),
    allocation_status VARCHAR(20) NOT NULL DEFAULT 'Partial'
        CHECK (allocation_status IN ('Partial','Full','Released','Cancelled'))
);

-- ================================================================
-- 11. DISPATCH & INVOICING
-- ================================================================

CREATE TABLE IF NOT EXISTS dispatch (
    dispatch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES customer_order(order_id),
    vehicle_id BIGINT REFERENCES vehicle(vehicle_id),
    driver_id BIGINT REFERENCES driver(driver_id),
    dispatch_number VARCHAR(50) NOT NULL UNIQUE,
    dispatch_date DATE NOT NULL DEFAULT CURRENT_DATE,
    expected_delivery_date DATE,
    actual_delivery_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Prepared'
        CHECK (status IN ('Prepared','Dispatched','Delivered','Cancelled')),
    carrier VARCHAR(150),
    shipping_method VARCHAR(100),
    tracking_number VARCHAR(150),
    created_by BIGINT REFERENCES app_user(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_dispatch_dates
        CHECK (actual_delivery_date IS NULL OR actual_delivery_date >= dispatch_date)
);

CREATE TABLE IF NOT EXISTS dispatch_item (
    dispatch_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispatch_id BIGINT NOT NULL REFERENCES dispatch(dispatch_id) ON DELETE CASCADE,
    allocation_id BIGINT NOT NULL REFERENCES order_allocation(allocation_id),
    finished_batch_id BIGINT NOT NULL REFERENCES finished_batch(finished_batch_id),
    quantity NUMERIC(18,4) NOT NULL CHECK (quantity > 0)
);

CREATE TABLE IF NOT EXISTS invoice (
    invoice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispatch_id BIGINT NOT NULL UNIQUE REFERENCES dispatch(dispatch_id),
    customer_id BIGINT NOT NULL REFERENCES customer(customer_id),
    customer_name_snapshot VARCHAR(150),
    customer_gst_snapshot VARCHAR(30),
    billing_address_snapshot JSONB,
    invoice_number VARCHAR(50) NOT NULL UNIQUE,
    invoice_date DATE NOT NULL DEFAULT CURRENT_DATE,
    subtotal NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    discount_amount NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    taxable_amount NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (taxable_amount >= 0),
    tax_amount NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    grand_total NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (grand_total >= 0),
    payment_status VARCHAR(30),
    due_date DATE
);

CREATE TABLE IF NOT EXISTS invoice_item (
    invoice_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoice(invoice_id) ON DELETE CASCADE,
    dispatch_item_id BIGINT NOT NULL REFERENCES dispatch_item(dispatch_item_id),
    quantity NUMERIC(18,4) NOT NULL CHECK (quantity > 0),
    rate NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (rate >= 0),
    CONSTRAINT uq_invoice_dispatch_item UNIQUE (invoice_id, dispatch_item_id)
);

-- ================================================================
-- 12. AI & ANALYTICS
-- ================================================================

CREATE TABLE IF NOT EXISTS forecast_model (
    model_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR(150) NOT NULL,
    model_version VARCHAR(50) NOT NULL,
    model_type VARCHAR(30) NOT NULL
        CHECK (model_type IN ('MovingAvg','ARIMA','XGBoost','LSTM','Transformer')),
    accuracy_score NUMERIC(7,4) CHECK (accuracy_score >= 0),
    training_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Training'
        CHECK (status IN ('Training','Active','Retired')),
    CONSTRAINT uq_forecast_model_version UNIQUE (model_name, model_version)
);

CREATE TABLE IF NOT EXISTS forecast_run (
    forecast_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id BIGINT NOT NULL REFERENCES forecast_model(model_id),
    plant_id BIGINT NOT NULL REFERENCES plant(plant_id),
    run_date DATE NOT NULL DEFAULT CURRENT_DATE,
    forecast_horizon VARCHAR(20) NOT NULL
        CHECK (forecast_horizon IN ('Daily','Weekly','Monthly')),
    status VARCHAR(20) NOT NULL DEFAULT 'Running'
        CHECK (status IN ('Running','Completed','Failed'))
);

CREATE TABLE IF NOT EXISTS forecast_result (
    forecast_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forecast_run_id BIGINT NOT NULL REFERENCES forecast_run(forecast_run_id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES finished_product(product_id),
    forecast_date DATE NOT NULL,
    predicted_quantity NUMERIC(18,4) NOT NULL CHECK (predicted_quantity >= 0),
    confidence_score NUMERIC(7,4) CHECK (confidence_score >= 0 AND confidence_score <= 1),
    lower_bound NUMERIC(18,4),
    upper_bound NUMERIC(18,4),
    CONSTRAINT uq_forecast_result UNIQUE (forecast_run_id, product_id, forecast_date),
    CONSTRAINT chk_forecast_bounds
        CHECK (lower_bound IS NULL OR upper_bound IS NULL OR lower_bound <= upper_bound)
);

CREATE TABLE IF NOT EXISTS purchase_recommendation (
    recommendation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id BIGINT NOT NULL REFERENCES raw_material(material_id),
    plant_id BIGINT NOT NULL REFERENCES plant(plant_id),
    supplier_material_id BIGINT REFERENCES supplier_material(supplier_material_id),
    converted_po_id BIGINT REFERENCES purchase_order(po_id),
    recommended_date DATE NOT NULL DEFAULT CURRENT_DATE,
    recommended_qty NUMERIC(18,4) NOT NULL CHECK (recommended_qty > 0),
    estimated_cost NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (estimated_cost >= 0),
    safety_stock NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (safety_stock >= 0),
    current_stock NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (current_stock >= 0),
    lead_time_days INTEGER NOT NULL DEFAULT 0 CHECK (lead_time_days >= 0),
    priority VARCHAR(20) NOT NULL DEFAULT 'Medium'
        CHECK (priority IN ('Low','Medium','High','Critical')),
    reason TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'New'
        CHECK (status IN ('New','InReview','Approved','Converted','Rejected')),
    approved_by BIGINT REFERENCES app_user(user_id),
    approved_at TIMESTAMPTZ
);

-- ================================================================
-- 13. IoT / EDGE TELEMETRY
-- ================================================================

CREATE TABLE IF NOT EXISTS iot_device (
    device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id BIGINT REFERENCES machine(machine_id),
    device_code VARCHAR(100) NOT NULL UNIQUE,
    device_type VARCHAR(100) NOT NULL,
    protocol VARCHAR(30) NOT NULL DEFAULT 'MQTT'
        CHECK (protocol IN ('MQTT','HTTP','OPC-UA','Other')),
    topic VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS telemetry_packet (
    telemetry_packet_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    packet_uuid UUID NOT NULL UNIQUE,
    device_id BIGINT NOT NULL REFERENCES iot_device(device_id),
    machine_id BIGINT REFERENCES machine(machine_id),
    event_timestamp TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    payload JSONB NOT NULL,
    processing_status VARCHAR(20) NOT NULL DEFAULT 'Received'
        CHECK (processing_status IN ('Received','Processed','Failed','Duplicate')),
    processed_at TIMESTAMPTZ,
    error_message TEXT
);

CREATE TABLE IF NOT EXISTS telemetry_measurement (
    measurement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL REFERENCES iot_device(device_id),
    machine_id BIGINT REFERENCES machine(machine_id),
    telemetry_packet_id BIGINT REFERENCES telemetry_packet(telemetry_packet_id) ON DELETE SET NULL,
    metric_name VARCHAR(100) NOT NULL,
    metric_value NUMERIC(24,8) NOT NULL,
    unit VARCHAR(30),
    event_timestamp TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS machine_event (
    machine_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id BIGINT NOT NULL REFERENCES machine(machine_id),
    device_id BIGINT REFERENCES iot_device(device_id),
    event_type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'Medium'
        CHECK (severity IN ('Low','Medium','High','Critical')),
    event_timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    payload JSONB,
    acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
    acknowledged_by BIGINT REFERENCES app_user(user_id),
    acknowledged_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ================================================================
-- 14. DOCUMENTS / TRACEABILITY
-- ================================================================

CREATE TABLE IF NOT EXISTS document (
    document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR(50) NOT NULL
        CHECK (document_type IN ('PO','Invoice','COA','GST','DeliveryReceipt','QCReport','ProductionReport','Other')),
    file_name VARCHAR(255) NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    mime_type VARCHAR(150),
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(100) NOT NULL,
    uploaded_by BIGINT REFERENCES app_user(user_id),
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS status_history (
    status_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(100) NOT NULL,
    old_status VARCHAR(100),
    new_status VARCHAR(100) NOT NULL,
    changed_by BIGINT REFERENCES app_user(user_id),
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remarks TEXT
);

CREATE TABLE IF NOT EXISTS integration_log (
    integration_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integration_name VARCHAR(150) NOT NULL,
    direction VARCHAR(20) NOT NULL CHECK (direction IN ('Inbound','Outbound')),
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(100),
    status VARCHAR(20) NOT NULL CHECK (status IN ('Success','Failed','Pending')),
    external_reference VARCHAR(150),
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_log (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES app_user(user_id) ON DELETE SET NULL,
    action VARCHAR(100) NOT NULL,
    module VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(100) NOT NULL,
    old_value JSONB,
    new_value JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ================================================================
-- 15. ALERTS & NOTIFICATIONS
-- ================================================================

CREATE TABLE IF NOT EXISTS alert (
    alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    alert_type VARCHAR(50) NOT NULL
        CHECK (alert_type IN (
            'LowStock','OverStock','Expiry','QualityFailure','ProductionDelay',
            'PurchaseDelay','OrderDelay','ForecastAnomaly','SystemError',
            'MachineFault','SensorFailure','TemperatureHigh','PressureHigh',
            'MachineStopped','TelemetryOffline','ProductionAnomaly','ScrapRateHigh'
        )),
    severity VARCHAR(20) NOT NULL DEFAULT 'Medium'
        CHECK (severity IN ('Low','Medium','High','Critical')),
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    entity_type VARCHAR(100),
    entity_id VARCHAR(100),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS notification (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id BIGINT NOT NULL REFERENCES alert(alert_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    channel VARCHAR(20) NOT NULL CHECK (channel IN ('Email','SMS','WhatsApp','InApp')),
    status VARCHAR(20) NOT NULL DEFAULT 'Pending'
        CHECK (status IN ('Pending','Sent','Failed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMPTZ,
    failure_reason TEXT
);

-- ================================================================
-- 16. CROSS-MODULE FOREIGN KEYS
-- ================================================================

ALTER TABLE inventory_transaction
    ADD CONSTRAINT fk_inventory_tx_dispatch_item
    FOREIGN KEY (dispatch_item_id)
    REFERENCES dispatch_item(dispatch_item_id);

ALTER TABLE inventory_reservation
    ADD CONSTRAINT fk_inventory_reservation_order_item
    FOREIGN KEY (order_item_id)
    REFERENCES customer_order_item(order_item_id);

-- ================================================================
-- 17. INDEXES
-- ================================================================

CREATE INDEX IF NOT EXISTS idx_warehouse_plant ON warehouse(plant_id);
CREATE INDEX IF NOT EXISTS idx_rack_warehouse ON location_rack(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_shelf_rack ON location_shelf(rack_id);
CREATE INDEX IF NOT EXISTS idx_bin_shelf ON location_bin(shelf_id);

CREATE INDEX IF NOT EXISTS idx_raw_material_category ON raw_material(category_id);
CREATE INDEX IF NOT EXISTS idx_product_category ON finished_product(prod_cat_id);
CREATE INDEX IF NOT EXISTS idx_product_spec_product ON product_specification(product_id);

CREATE INDEX IF NOT EXISTS idx_user_plant ON app_user(plant_id);
CREATE INDEX IF NOT EXISTS idx_user_role_user ON user_role(user_id);
CREATE INDEX IF NOT EXISTS idx_role_permission_role ON role_permission(role_id);

CREATE INDEX IF NOT EXISTS idx_supplier_material_supplier ON supplier_material(supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_material_material ON supplier_material(material_id);
CREATE INDEX IF NOT EXISTS idx_po_supplier_date ON purchase_order(supplier_id, po_date);
CREATE INDEX IF NOT EXISTS idx_po_item_material ON purchase_order_item(material_id);
CREATE INDEX IF NOT EXISTS idx_gr_po ON goods_receipt(po_id);

CREATE INDEX IF NOT EXISTS idx_batch_material ON material_batch(material_id);
CREATE INDEX IF NOT EXISTS idx_batch_supplier ON material_batch(supplier_id);
CREATE INDEX IF NOT EXISTS idx_batch_quality_status ON material_batch(quality_status);

CREATE INDEX IF NOT EXISTS idx_compounding_batch_bom ON compounding_batch(compounding_bom_id);
CREATE INDEX IF NOT EXISTS idx_compounding_batch_material_batch ON compounding_batch_material(material_batch_id);
CREATE INDEX IF NOT EXISTS idx_production_unit_plant ON production_unit(plant_id);
CREATE INDEX IF NOT EXISTS idx_machine_unit ON machine(unit_id);
CREATE INDEX IF NOT EXISTS idx_machine_status ON machine(status);

CREATE INDEX IF NOT EXISTS idx_production_plant_status ON production_run(plant_id, status);
CREATE INDEX IF NOT EXISTS idx_production_material_batch ON production_material(batch_id);
CREATE INDEX IF NOT EXISTS idx_production_stage_production ON production_stage(production_id);
CREATE INDEX IF NOT EXISTS idx_production_stage_status ON production_stage(status);
CREATE INDEX IF NOT EXISTS idx_unit_operation_production ON unit_operation(production_id);
CREATE INDEX IF NOT EXISTS idx_unit_operation_machine ON unit_operation(machine_id);
CREATE INDEX IF NOT EXISTS idx_unit_operation_logged_at ON unit_operation(logged_at);

CREATE INDEX IF NOT EXISTS idx_finished_batch_product ON finished_batch(product_id);
CREATE INDEX IF NOT EXISTS idx_finished_batch_quality ON finished_batch(quality_status);
CREATE INDEX IF NOT EXISTS idx_genealogy_finished_batch ON batch_genealogy(finished_batch_id);
CREATE INDEX IF NOT EXISTS idx_genealogy_raw_batch ON batch_genealogy(raw_material_batch_id);
CREATE INDEX IF NOT EXISTS idx_genealogy_compounding_batch ON batch_genealogy(compounding_batch_id);
CREATE INDEX IF NOT EXISTS idx_genealogy_operation ON batch_genealogy(unit_operation_id);

CREATE INDEX IF NOT EXISTS idx_inventory_material_batch ON inventory(material_batch_id);
CREATE INDEX IF NOT EXISTS idx_inventory_finished_batch ON inventory(finished_batch_id);
CREATE INDEX IF NOT EXISTS idx_inventory_bin ON inventory(bin_id);

CREATE INDEX IF NOT EXISTS idx_inventory_tx_date ON inventory_transaction(transaction_date);
CREATE INDEX IF NOT EXISTS idx_inventory_tx_type ON inventory_transaction(transaction_type);
CREATE INDEX IF NOT EXISTS idx_inventory_tx_inventory ON inventory_transaction(inventory_id);

CREATE INDEX IF NOT EXISTS idx_ledger_tx_date ON inventory_ledger_transaction(transaction_date);
CREATE INDEX IF NOT EXISTS idx_ledger_tx_type ON inventory_ledger_transaction(transaction_type);
CREATE INDEX IF NOT EXISTS idx_ledger_entry_transaction ON inventory_ledger_entry(ledger_transaction_id);
CREATE INDEX IF NOT EXISTS idx_ledger_entry_inventory ON inventory_ledger_entry(inventory_id);

CREATE INDEX IF NOT EXISTS idx_transfer_source ON stock_transfer(from_warehouse_id);
CREATE INDEX IF NOT EXISTS idx_transfer_destination ON stock_transfer(to_warehouse_id);

CREATE INDEX IF NOT EXISTS idx_qc_material_batch ON quality_inspection(material_batch_id);
CREATE INDEX IF NOT EXISTS idx_qc_production ON quality_inspection(production_id);
CREATE INDEX IF NOT EXISTS idx_qc_finished_batch ON quality_inspection(finished_batch_id);
CREATE INDEX IF NOT EXISTS idx_qc_item_inspection ON quality_inspection_item(inspection_id);

CREATE INDEX IF NOT EXISTS idx_pallet_warehouse ON pallet(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_pallet_bin ON pallet(bin_id);
CREATE INDEX IF NOT EXISTS idx_pallet_item_batch ON pallet_item(finished_batch_id);

CREATE INDEX IF NOT EXISTS idx_order_customer ON customer_order(customer_id);
CREATE INDEX IF NOT EXISTS idx_order_status ON customer_order(status);
CREATE INDEX IF NOT EXISTS idx_order_item_product ON customer_order_item(product_id);
CREATE INDEX IF NOT EXISTS idx_allocation_order_item ON order_allocation(order_item_id);
CREATE INDEX IF NOT EXISTS idx_allocation_finished_batch ON order_allocation(finished_batch_id);

CREATE INDEX IF NOT EXISTS idx_dispatch_order ON dispatch(order_id);
CREATE INDEX IF NOT EXISTS idx_dispatch_status ON dispatch(status);
CREATE INDEX IF NOT EXISTS idx_dispatch_item_batch ON dispatch_item(finished_batch_id);
CREATE INDEX IF NOT EXISTS idx_invoice_customer ON invoice(customer_id);

CREATE INDEX IF NOT EXISTS idx_forecast_run_model ON forecast_run(model_id);
CREATE INDEX IF NOT EXISTS idx_forecast_run_plant ON forecast_run(plant_id);
CREATE INDEX IF NOT EXISTS idx_forecast_result_product_date ON forecast_result(product_id, forecast_date);
CREATE INDEX IF NOT EXISTS idx_purchase_recommendation_material ON purchase_recommendation(material_id);
CREATE INDEX IF NOT EXISTS idx_purchase_recommendation_status ON purchase_recommendation(status);

CREATE INDEX IF NOT EXISTS idx_iot_device_machine ON iot_device(machine_id);
CREATE INDEX IF NOT EXISTS idx_iot_device_last_seen ON iot_device(last_seen_at);
CREATE INDEX IF NOT EXISTS idx_telemetry_packet_device_time ON telemetry_packet(device_id, event_timestamp);
CREATE INDEX IF NOT EXISTS idx_telemetry_packet_status ON telemetry_packet(processing_status);
CREATE INDEX IF NOT EXISTS idx_telemetry_measurement_device_time ON telemetry_measurement(device_id, event_timestamp);
CREATE INDEX IF NOT EXISTS idx_telemetry_measurement_metric_time ON telemetry_measurement(metric_name, event_timestamp);
CREATE INDEX IF NOT EXISTS idx_machine_event_machine_time ON machine_event(machine_id, event_timestamp);
CREATE INDEX IF NOT EXISTS idx_machine_event_unack ON machine_event(acknowledged, event_timestamp);

CREATE INDEX IF NOT EXISTS idx_status_history_entity ON status_history(entity_type, entity_id, changed_at);
CREATE INDEX IF NOT EXISTS idx_integration_log_entity ON integration_log(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_integration_log_status ON integration_log(status);
CREATE INDEX IF NOT EXISTS idx_audit_log_entity ON audit_log(entity_type, entity_id, created_at);
CREATE INDEX IF NOT EXISTS idx_alert_user_read ON alert(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_notification_user ON notification(user_id);

-- ================================================================
-- 18. UPDATED_AT TRIGGERS
-- ================================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_plant_updated_at ON plant;
CREATE TRIGGER trg_plant_updated_at
BEFORE UPDATE ON plant
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_raw_material_updated_at ON raw_material;
CREATE TRIGGER trg_raw_material_updated_at
BEFORE UPDATE ON raw_material
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_finished_product_updated_at ON finished_product;
CREATE TRIGGER trg_finished_product_updated_at
BEFORE UPDATE ON finished_product
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_product_spec_updated_at ON product_specification;
CREATE TRIGGER trg_product_spec_updated_at
BEFORE UPDATE ON product_specification
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_supplier_updated_at ON supplier;
CREATE TRIGGER trg_supplier_updated_at
BEFORE UPDATE ON supplier
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_customer_updated_at ON customer;
CREATE TRIGGER trg_customer_updated_at
BEFORE UPDATE ON customer
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_purchase_order_updated_at ON purchase_order;
CREATE TRIGGER trg_purchase_order_updated_at
BEFORE UPDATE ON purchase_order
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_compounding_bom_updated_at ON compounding_bom;
CREATE TRIGGER trg_compounding_bom_updated_at
BEFORE UPDATE ON compounding_bom
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_machine_updated_at ON machine;
CREATE TRIGGER trg_machine_updated_at
BEFORE UPDATE ON machine
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_production_updated_at ON production_run;
CREATE TRIGGER trg_production_updated_at
BEFORE UPDATE ON production_run
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_inventory_updated_at ON inventory;
CREATE TRIGGER trg_inventory_updated_at
BEFORE UPDATE ON inventory
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_iot_device_updated_at ON iot_device;
CREATE TRIGGER trg_iot_device_updated_at
BEFORE UPDATE ON iot_device
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ================================================================
-- 19. INVENTORY / LEDGER SAFETY FUNCTIONS
-- ================================================================

CREATE OR REPLACE FUNCTION validate_inventory_update()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.quantity_on_hand < 0 THEN
        RAISE EXCEPTION 'quantity_on_hand cannot be negative';
    END IF;

    IF NEW.reserved_qty < 0 THEN
        RAISE EXCEPTION 'reserved_qty cannot be negative';
    END IF;

    IF NEW.reserved_qty > NEW.quantity_on_hand THEN
        RAISE EXCEPTION
            'reserved_qty (%) cannot exceed quantity_on_hand (%)',
            NEW.reserved_qty, NEW.quantity_on_hand;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_inventory_validate ON inventory;
CREATE TRIGGER trg_inventory_validate
BEFORE INSERT OR UPDATE OF quantity_on_hand, reserved_qty
ON inventory
FOR EACH ROW EXECUTE FUNCTION validate_inventory_update();

CREATE OR REPLACE FUNCTION prevent_inventory_transaction_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION
        'inventory_transaction is an append-only ledger; % is not allowed',
        TG_OP;
END;
$$;

DROP TRIGGER IF EXISTS trg_inventory_transaction_immutable ON inventory_transaction;
CREATE TRIGGER trg_inventory_transaction_immutable
BEFORE UPDATE OR DELETE ON inventory_transaction
FOR EACH ROW EXECUTE FUNCTION prevent_inventory_transaction_mutation();

CREATE OR REPLACE FUNCTION validate_double_entry_ledger()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    debit_total NUMERIC(30,8);
    credit_total NUMERIC(30,8);
    entry_count INTEGER;
    target_transaction_id BIGINT;
BEGIN
    target_transaction_id := COALESCE(NEW.ledger_transaction_id, OLD.ledger_transaction_id);

    SELECT
        COUNT(*),
        COALESCE(SUM(quantity) FILTER (WHERE entry_type = 'DEBIT'), 0),
        COALESCE(SUM(quantity) FILTER (WHERE entry_type = 'CREDIT'), 0)
    INTO entry_count, debit_total, credit_total
    FROM inventory_ledger_entry
    WHERE ledger_transaction_id = target_transaction_id;

    IF entry_count < 2 OR debit_total <> credit_total THEN
        RAISE EXCEPTION
            'Inventory ledger transaction % is not balanced: entries=%, debit=%, credit=%',
            target_transaction_id, entry_count, debit_total, credit_total;
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_double_entry_ledger ON inventory_ledger_entry;
CREATE CONSTRAINT TRIGGER trg_validate_double_entry_ledger
AFTER INSERT OR UPDATE OR DELETE ON inventory_ledger_entry
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_double_entry_ledger();

COMMIT;
